version: "3.5"

services:
  consul:
    image: consul
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
    networks:
      - consul-net

  api-gateway:
    restart: on-failure
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - consul-net
    depends_on:
      - consul

  hello-service:
    restart: on-failure
    build:
      context: ./hello-service
      dockerfile: Dockerfile
    networks:
      - consul-net
    depends_on:
      - consul

  bye-service:
    restart: on-failure
    build:
      context: ./bye-service
      dockerfile: Dockerfile
    networks:
      - consul-net
    depends_on:
      - consul

networks:
  consul-net:
    driver: bridge
