spring:
  application:
    name: api-gateway
  
  cloud:
    consul:
      enabled: true
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${server.port}:${random.value}
      host: consul
      port: 8500

server:
  port: 8080
  address: 0.0.0.0

camel:
  cloud:
    consul:
      service-discovery:
        enabled: true
        url: http://consul:8500
    service-call:
      component: undertow
  rest:
    component: servlet
    binding-mode: auto
  component:
    servlet:
      mapping:
        context-path: /api/*
    properties:
      auto-discover-properties-sources: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
 
logging.level:
    org.springframework.cloud:
      consul: DEBUG